set(OpenCV_VERSION 3.4.4)
set(OpenCV_VERSION_MAJOR 3)
set(OpenCV_VERSION_MINOR 4)
set(OpenCV_VERSION_PATCH 4)
set(OpenCV_SHARED ON)
set(OpenCV_CONFIG_PATH /usr/local/share/OpenCV)
set(OpenCV_INSTALL_PATH /usr/local)
set(OpenCV_LIB_COMPONENTS opencv_dnn;opencv_photo;opencv_videoio;opencv_objdetect;opencv_ml;opencv_video;opencv_calib3d;opencv_superres;opencv_shape;opencv_videostab;opencv_core;opencv_flann;opencv_imgproc;opencv_highgui;opencv_viz;opencv_stitching;opencv_features2d;opencv_imgcodecs;opencv_surface_matching;opencv_xphoto;opencv_optflow;opencv_img_hash;opencv_xfeatures2d;opencv_datasets;opencv_ximgproc;opencv_plot;opencv_structured_light;opencv_face;opencv_tracking;opencv_fuzzy;opencv_dnn_objdetect;opencv_hfs;opencv_bioinspired;opencv_dpm;opencv_xobjdetect;opencv_phase_unwrapping;opencv_aruco;opencv_ccalib;opencv_freetype;opencv_rgbd;opencv_line_descriptor;opencv_bgsegm;opencv_saliency;opencv_text;opencv_reg;opencv_stereo;opencv_hdf)
set(OpenCV_USE_MANGLED_PATHS FALSE)
set(OpenCV_MODULES_SUFFIX )


