// Generated by gencpp from file joysticks/grip.msg
// DO NOT EDIT!


#ifndef JOYSTICKS_MESSAGE_GRIP_H
#define JOYSTICKS_MESSAGE_GRIP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace joysticks
{
template <class ContainerAllocator>
struct grip_
{
  typedef grip_<ContainerAllocator> Type;

  grip_()
    : grip(0)
    , roll(0)
    , pan(0)  {
    }
  grip_(const ContainerAllocator& _alloc)
    : grip(0)
    , roll(0)
    , pan(0)  {
  (void)_alloc;
    }



   typedef int16_t _grip_type;
  _grip_type grip;

   typedef int16_t _roll_type;
  _roll_type roll;

   typedef int16_t _pan_type;
  _pan_type pan;





  typedef boost::shared_ptr< ::joysticks::grip_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::joysticks::grip_<ContainerAllocator> const> ConstPtr;

}; // struct grip_

typedef ::joysticks::grip_<std::allocator<void> > grip;

typedef boost::shared_ptr< ::joysticks::grip > gripPtr;
typedef boost::shared_ptr< ::joysticks::grip const> gripConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::joysticks::grip_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::joysticks::grip_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace joysticks

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'joysticks': ['/home/adam/catkin_ws/src/joysticks/msg', '/home/adam/catkin_ws/src/joysticks/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::joysticks::grip_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::joysticks::grip_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::joysticks::grip_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::joysticks::grip_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joysticks::grip_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joysticks::grip_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::joysticks::grip_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0cbb4ca42bcf7d679dd2c2e5b180f1c";
  }

  static const char* value(const ::joysticks::grip_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0cbb4ca42bcf7d6ULL;
  static const uint64_t static_value2 = 0x79dd2c2e5b180f1cULL;
};

template<class ContainerAllocator>
struct DataType< ::joysticks::grip_<ContainerAllocator> >
{
  static const char* value()
  {
    return "joysticks/grip";
  }

  static const char* value(const ::joysticks::grip_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::joysticks::grip_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 grip\n\
int16 roll\n\
int16 pan\n\
";
  }

  static const char* value(const ::joysticks::grip_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::joysticks::grip_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grip);
      stream.next(m.roll);
      stream.next(m.pan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct grip_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::joysticks::grip_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::joysticks::grip_<ContainerAllocator>& v)
  {
    s << indent << "grip: ";
    Printer<int16_t>::stream(s, indent + "  ", v.grip);
    s << indent << "roll: ";
    Printer<int16_t>::stream(s, indent + "  ", v.roll);
    s << indent << "pan: ";
    Printer<int16_t>::stream(s, indent + "  ", v.pan);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JOYSTICKS_MESSAGE_GRIP_H
